### ISSUE TITLE
[BUG] Fails to complete a scan

### ISSUE THREAD

**Issue by Iletee** [sonatype-nexus-community/auditjs#134]
**Description**
Running a scan on a project fails - an error message is produced and scan never completes 

Using a existing appid in my IQ server

```
Ilkkas-MacBook-Pro:juice-shop ilkkaturunen$ auditjs iq -a 1422 -s develop
 ________  ___  ___  ________  ___  _________      ___  ________
|\   __  \|\  \|\  \|\   ___ \|\  \|\___   ___\   |\  \|\   ____\
\ \  \|\  \ \  \\\  \ \  \_|\ \ \  \|___ \  \_|   \ \  \ \  \___|_
 \ \   __  \ \  \\\  \ \  \ \\ \ \  \   \ \  \  __ \ \  \ \_____  \
  \ \  \ \  \ \  \\\  \ \  \_\\ \ \  \   \ \  \|\  \\_\  \|____|\  \
   \ \__\ \__\ \_______\ \_______\ \__\   \ \__\ \________\____\_\  \
    \|__|\|__|\|_______|\|_______|\|__|    \|__|\|________|\_________\
                                                          \|_________|


✔ Starting application
✔ Getting coordinates for Nexus IQ Server
✔ Auditing your application with Nexus IQ Server
✔ Getting your internal application ID
✔ Submitting your dependencies to Nexus IQ Server
⠋ Checking for results (this could take a minute)(node:4274) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at IqRequestService.getURLOrMerge (/usr/local/lib/node_modules/auditjs/bin/Services/IqRequestService.js:120:13)
    at IqRequestService.<anonymous> (/usr/local/lib/node_modules/auditjs/bin/Services/IqRequestService.js:92:62)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/auditjs/bin/Services/IqRequestService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/auditjs/bin/Services/IqRequestService.js:4:12)
    at IqRequestService.asyncPollForResults (/usr/local/lib/node_modules/auditjs/bin/Services/IqRequestService.js:90:16)
    at Application.<anonymous> (/usr/local/lib/node_modules/auditjs/bin/Application/Application.js:210:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/auditjs/bin/Application/Application.js:5:58)
(node:4274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠹ Checking for results (this could take a minute)`
```

**To reproduce**
Git Clone this: https://github.com/bkimminich/juice-shop
Install auditjs & config with iq
Running auditjs iq 
Hangs and crashes

**Environment** 
See issue number #132

**Comment by DarthHater** [comment]
This ended up being that @Iletee had an older version of nodejs, I believe 8.x era. @allenhsieh is looking at it and seeing if we have a quick fix, otherwise we will update the package.json to reflect we only support from node 10.x forward

**Comment by DarthHater** [comment]
Well, @allenhsieh is an awesome person and figured this out. `URL` is not a global object in node 8.x, that didn't happen till 10.x, so we are testing explicitly importing it so we can support 8.x forward. Doubtful we'd go further back than 8.x, since 8.x LTS maintenance just ended, but posting this comment for future posterity.

I believe @allenhsieh plans on setting `engines` in our `package.json` to at least warn someone if they are not on 8.x forward.

**Comment by DarthHater** [comment]
@Iletee we made changes to explicitly support node 8.x forward (thanks to @allenhsieh again), you can retest and close this at your leisure.
