### ISSUE TITLE
Error: Unable to submit to Third Party API

### ISSUE THREAD

**Issue by derek-sonatype** [sonatype-nexus-community/auditjs#157]
I am on a Windows 10 machine running this in PowerShell. My node version is v12.14.1. I have tried to run auditjs iq -s build -a juiceshop --server http://localhost:8070 -u admin -p admin123 both with Windows Firewall on (allowed apps to run) and with it completely turned off with the same error. Here is the output:

```
PS C:\Users\devel\projects\juiceshop\juice-shop> auditjs iq -s build -a juiceshop --server http://localhost:8070 -u admin -p admin123
 ________   ___  ___   ________   ___   _________       ___   ________
|\   __  \ |\  \|\  \ |\   ___ \ |\  \ |\___   ___\    |\  \ |\   ____\
\ \  \|\  \\ \  \\\  \\ \  \_|\ \\ \  \\|___ \  \_|    \ \  \\ \  \___|_
 \ \   __  \\ \  \\\  \\ \  \ \\ \\ \  \    \ \  \   __ \ \  \\ \_____  \
  \ \  \ \  \\ \  \\\  \\ \  \_\\ \\ \  \    \ \  \ |\  \\_\  \\|____|\  \
   \ \__\ \__\\ \_______\\ \_______\\ \__\    \ \__\\ \________\ ____\_\  \
    \|__|\|__| \|_______| \|_______| \|__|     \|__| \|________||\_________\
                                                                \|_________|


  _      _                       _   _
 /_)    /_`_  _  _ _/_   _  _   (/  /_`_._  _   _/ _
/_)/_/ ._//_// //_|/ /_//_//_' (_X /  ///_'/ //_/_\
   _/                _//

  AuditJS version: 4.0.1-beta.24

√ Starting application
√ Getting coordinates for Sonatype IQ
√ Auditing your application with Sonatype IQ
√ Authenticating with Sonatype IQ
× Submitting your dependencies
{
  '0': {
    title: 'Unable to submit to Third Party API',
    stack: 'Error: Unable to submit to Third Party API\n' +
      '    at IqRequestService.<anonymous> (C:\\Users\\devel\\AppData\\Roaming\\npm\\node_modules\\auditjs\\bin\\Services\\IqRequestService.js:83:23)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (C:\\Users\\devel\\AppData\\Roaming\\npm\\node_modules\\auditjs\\bin\\Services\\IqRequestService.js:5:58)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:94:5)'
  },
  level: 'error',
  message: 'There was an issue auditing your application!',
  label: 'AuditJS',
  timestamp: '2020-02-13T13:49:41.595Z'
}
```

[.audit-js.combined.log](https://github.com/sonatype-nexus-community/auditjs/files/4198786/default.audit-js.combined.log)

**Comment by KevinFauth** [comment]
I am getting this error as well (names changed to protect the innocent):
```javascript
$ node ./node_modules/auditjs/bin/index.js iq -h https://nexus-id-server-path.com -a my-project-name -u "sample_user" -p "*****" -s develop
________   ___  ___   ________   ___   _________       ___   ________     
|\   __  \ |\  \|\  \ |\   ___ \ |\  \ |\___   ___\    |\  \ |\   ____\    
\ \  \|\  \\ \  \\\  \\ \  \_|\ \\ \  \\|___ \  \_|    \ \  \\ \  \___|_   
 \ \   __  \\ \  \\\  \\ \  \ \\ \\ \  \    \ \  \   __ \ \  \\ \_____  \  
  \ \  \ \  \\ \  \\\  \\ \  \_\\ \\ \  \    \ \  \ |\  \\_\  \\|____|\  \ 
   \ \__\ \__\\ \_______\\ \_______\\ \__\    \ \__\\ \________\ ____\_\  \
    \|__|\|__| \|_______| \|_______| \|__|     \|__| \|________||\_________\
                                                                \|_________|
                                                                           
                                                                            
  _      _                       _   _             
 /_)    /_`_  _  _ _/_   _  _   (/  /_`_._  _   _/ _
/_)/_/ ._//_// //_|/ /_//_//_' (_X /  ///_'/ //_/_\
   _/                _//                           
AuditJS version: 4.0.1-beta.23
✔ Starting application
✔ Getting coordinates for Sonatype IQ
✔ Auditing your application with Sonatype IQ
✔ Authenticating with Sonatype IQ
⠋ Submitting your dependencies
⠇ Submitting your dependencies
⠴ Submitting your dependenciesResponse {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://nexus-id-server-path.com/api/v2/scan/applications/0be601ebe7954f9192981748490e4cfc/sources/auditjs?stageId=develop',
    status: 404,
    statusText: 'Not Found',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
✖ Submitting your dependencies
{
  '0': {
    title: 'Unable to submit to Third Party API',
    stack: 'Error: Unable to submit to Third Party API\n' +
      '    at IqRequestService.<anonymous> (***/node_modules/auditjs/bin/Services/IqRequestService.js:85:23)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (***/node_modules/auditjs/bin/Services/IqRequestService.js:5:58)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:94:5)'
  },
  level: 'error',
  message: 'There was an issue auditing your application!',
  label: 'AuditJS',
  timestamp: '2020-02-13T16:14:19.909Z'
}
$
```

**Comment by DarthHater** [comment]
Hi @KevinFauth , @derek-sonatype , thanks for filing an issue, and thanks for trying out the beta, too!

My first thoughts are, what version of Nexus IQ Server are you running? 404 not found on that url would indicate to me that maybe you are running a version that doesn't have the third party API (I think that was previous to version 78, ideally you'd run 83 as the team working on that functionality has made a lot of changes we lean on). 

That said, I also added some more logging this morning so I could get more detail (that you've handily provided, which makes it almost moot, hah).

**Comment by KevinFauth** [comment]
Ah - that makes sense. It looks like we're on 74. Maybe add the IQ server version as a pre-req to the readme?

In the meantime, I'll see what I can do about getting mine updated to 83 - I'm sure it'll be quick and easy </sarcasm> #corporate

**Comment by DarthHater** [comment]
@KevinFauth you read my mind, @allenhsieh is on it right now!

I unfortunately do not have any mystical fixes for corporate IT, but my love and blessings are with you :)

**Comment by DarthHater** [comment]
README update in, thanks again @KevinFauth .

Now, @derek-sonatype I think your issue has something to do with Windows, if you wouldn't mind rerunning beta with more logging so I can get a better look, that would be super helpful. Trying to figure out what went sideways for you!

**Comment by ButterB0wl** [comment]
@derek-sonatype do you mind pulling down the latest version of the beta `npm install -g auditjs@beta` and see if it works now?  We've pushed up a few changes

**Comment by derek-sonatype** [comment]
Fix works. Thank you.
