### ISSUE TITLE
[BUG] AuditJS requires Developer role on the application

### ISSUE THREAD

**Issue by instinet-lewis-boon** [sonatype-nexus-community/auditjs#218]
**Describe the bug**

AuditJS fails with the following if it hasn't been given the Developer role on the application.

```
[2020-12-04T15:16:17.598] [ERROR] auditjs - There was an issue auditing your application! Error: Error: No valid ID on response from Nexus IQ, potentially check the public application ID you are using
    at IqRequestService.<anonymous> (/home/node/.npm/_npx/70/lib/node_modules/auditjs/bin/Services/IqRequestService.js:54:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/node/.npm/_npx/70/lib/node_modules/auditjs/bin/Services/IqRequestService.js:21:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**

1. Setup an account. Add it as a `Application Evaulator` for the application you want to scan.
2. Run AuditJS with the account. **It will fail with the above error.**
3. Now add the application as a `Developer`
4. The scan will execute successfully.

**Expected behavior**

The Nexus IQ evaluator jar works with only the Application Evaluator role. It would be good to have the same consistency with AuditJS. 

**Desktop (please complete the following information):**
- Linux. CentOS 7. Node 10.

**Comment by DarthHater** [comment]
@instinet-lewis-boon I'll forward this to the team that works on IQ, I believe it's because we use two different APIs. AuditJS uses what is referred to as the Third Party API. Thanks for filing an issue!

**Comment by DarthHater** [comment]
Couple questions for you:

- What version of IQ server are you using
- You mean adding the application itself, as a user with those permissions, inside of IQ server is causing this issue?

**Comment by instinet-lewis-boon** [comment]
Hi, sorry for the slow reply. We're using Nexus IQ v102.

So we've been previously using the Nexus IQ Evaluator `jar` to scan application's node_modules directory. We created a user in Nexus IQ to do this. It was given the `Application Evaluator` role on the application. This works successfully.

When trying out AuditJS, the same credentials didn't work until we gave the user the `Developer` role.

Does that help?

**Comment by DarthHater** [comment]
Yes, that helps quite a bit! I'll check with some people and see what I can figure out.

**Comment by bhamail** [comment]
FWIW, I confirmed this is still an issue, and adding the `Developer` role fixes the the error.

Example from a Jenkins build:
```
Submitting your dependencies
[91m[2021-07-27T16:49:36.305] [ERROR] auditjs - [39mThere was an issue auditing your application! Error: Error: No valid ID on response from Nexus IQ, potentially check the public application ID you are using
    at IqRequestService.<anonymous> (/home/pi/.npm/_npx/9095/lib/node_modules/auditjs/bin/Services/IqRequestService.js:55:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/pi/.npm/_npx/9095/lib/node_modules/auditjs/bin/Services/IqRequestService.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Build step 'Execute shell' marked build as failure
```

**Comment by vinishakurapati** [comment]
@bhamail @DarthHater 
Hi, I am facing the same issue so I changed the role from "Application evaluator" to "Developer" but build is failing with a new error, Not sure what is causing this step failure, should the nexus user be given both developer and application evaluator role?
` ` `
C:\Jenkins\workspace\development_application -frontend>npx auditjs iq -a application id in IQ -s build -h http://grs-sonatype1.company-server.linux:8080/ -u **** -p **** 
npx: installed 105 in 19.408s

    \|__|\|__| \|_______| \|_______| \|__|     \|__| \|________||\_________\
                                                                \|_________|
                                                                            
                                                                            
  _      _                       _   _              
 /_)    /_`_  _  _ _/_   _  _   (/  /_`_._  _   _/ _
/_)/_/ ._//_// //_|/ /_//_//_' (_X /  ///_'/ //_/_\ 
   _/                _//                            

  AuditJS version: 4.0.37

- Starting application
âˆš Starting application
- Getting coordinates for Sonatype IQ
âˆš Getting coordinates for Sonatype IQ
- Auditing your application with Sonatype IQ
âˆš Auditing your application with Sonatype IQ
- Authenticating with Sonatype IQ
âˆš Authenticating with Sonatype IQ
- Submitting your dependencies
Ã— Submitting your dependencies
[91m[2022-05-04T01:37:18.832] [ERROR] auditjs - [39mThere was an issue auditing your application! Error: Unable to submit to Third Party API
    at IqRequestService.<anonymous> (C:\Users\jenkins\AppData\Roaming\npm-cache\_npx\8484\node_modules\auditjs\bin\Services\IqRequestService.js:104:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jenkins\AppData\Roaming\npm-cache\_npx\8484\node_modules\auditjs\bin\Services\IqRequestService.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Build step 'Execute Windows batch command' marked build as failure

` ` `

**Comment by vinishakurapati** [comment]
@bhamail   It works when the user is given both "developer" and "application evaluator", results can be  accessed through the link from console log of the build Which itself is very helpful for my project But  it shows no results in GUI of jenkins and GUI of Nexus  and when clicked the "view report" option. Wondering if it is the plugin Nexus platform issue or issue from nexus to validate plugin result.



![InkedCapture0034_LI](https://user-images.githubusercontent.com/86896425/166724892-b32e43cf-9ae5-40b5-81a2-51dd98aee25d.jpg)
<img width="558" alt="Capture9090" src="https://user-images.githubusercontent.com/86896425/166725009-f1aa5b74-f966-446e-8c5f-2192d1bf0285.PNG">

**Comment by madpah** [comment]
Thank you for the detailed report and for confirming the reproduction steps.

AuditJS uses the **Sonatype Lifecycle Third Party API** to submit scan results. This is a different API endpoint from the one used by the Nexus IQ Evaluator JAR (which uses the Evaluation API). The two APIs have different permission requirements:

- The **Evaluation API** (used by the Nexus IQ Evaluator JAR) works with the `Application Evaluator` role.
- The **Third Party API** (used by AuditJS) requires at minimum the `Developer` role on the target application in order to submit results.

This is a function of how the APIs are designed within Sonatype Lifecycle itself and is not something AuditJS can change on its side. The correct workaround is to ensure the user account running AuditJS has the `Developer` role on the target application.

Closing as **Not Planned** — the behaviour is by design. If the Sonatype Lifecycle API permission model changes in a future server release, please re-open or raise a new issue.
