### ISSUE TITLE
[BUG]Cannot install version 4.0.26 via yarn

### ISSUE THREAD

**Issue by yechenchao** [sonatype-nexus-community/auditjs#238]
**Describe the bug**
I am having issues with installing version 4.0.26 with yarn, it reports errors as below:

```
error /node_modules/auditjs: Command failed.
Exit code: 1
Command: npx npm-force-resolutions
Arguments: 
Directory: /node_modules/auditjs
Output:
npx: installed 6 in 2.851s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:476:3)
    at Object.fs [as readFileSync] (fs.js:377:35)

```

**To Reproduce**
run `yarn add auditjs@4.0.26`

**Expected behavior**
It should install without errors

**Desktop (please complete the following information):**
 - OS: macOS 11.4

**Additional context**
I did some investigation, and I think it's because version 4.0.26 added `preinstall:  npx npm-force-resolutions` which does not work with yarn by default? Please advise how can I resolve this issue.

cc @bhamail / @DarthHater / @allenhsieh / @Slim-Shary

**Comment by StickNitro** [comment]
Confirmed, I am getting the same in an Azure DevOps pipeline when executing `npm install -g auditjs`

```
> auditjs@4.0.26 preinstall /opt/hostedtoolcache/node/14.17.3/x64/lib/node_modules/auditjs
> npx npm-force-resolutions

npx: installed 6 in 1.531s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:498:3)
    at Object.fs [as readFileSync] (fs.js:394:35)
    at npm_force_resolutions$core$node_slurp (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/home/vsts/.npm/_npx/1624/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
```

**Comment by weichtg3** [comment]
Confirmed it's breaking for us too.  Same package-lock.json error... maybe removing that "-d" flag is the issue:
https://github.com/sonatype-nexus-community/auditjs/commit/9bb8efb8308dbae863a63066af61bbd767cec829

**Comment by yechenchao** [comment]
With latest auditjs 4.0.27 my issue has been resolved by adding `force-resolutions`.
